name: story
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  animate_do: ^3.3.3
  animated_bottom_navigation_bar: ^1.3.3
  animations: ^2.0.11
  another_flushbar: ^1.12.30
  bloc_concurrency: ^0.2.3
  bloc_test: ^9.1.6
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dropdown_button2: ^2.3.9
  easy_localization: ^3.0.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_cache_manager: ^3.3.1
  flutter_screenutil: ^5.9.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  geolocator: ^11.0.0
  get_it: ^7.6.7
  go_router: ^13.1.0
  google_maps_flutter: ^2.5.3
  http: ^1.2.0
  image_picker: ^1.0.7
  internet_connection_checker_plus: ^2.2.0
  json_annotation: ^4.8.1
  mocktail: ^1.0.3
  readmore: ^2.2.0
  shared_preferences: ^2.2.2
  slang: ^3.29.0
  slang_flutter: ^3.29.0
  very_good_analysis: ^5.1.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  slang_build_runner: ^3.29.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/astronout.svg
    - assets/svg/id.svg
    - assets/svg/en.svg
    - assets/translations/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
